### ISSUE TITLE
Resuming TCPDUMP on a previous capture.

### ISSUE THREAD

**Issue by fleezer94** [the-tcpdump-group/tcpdump#930] opened 2021-08-09 12:54 UTC
I cannot find any way to resume a capture on the same pcap file ..

**Comment by guyharris** [comment] 2021-08-09 22:02
Presumably you mean "I cannot find any way to start a capture and have it append to an existing capture file rather than creating a new capture file or overwriting an existing capture file".

**Comment by infrastation** [comment] 2021-08-11 16:30
tcpdump by design produces a .pcap file from scratch. If you need to merge several .pcap files together, please try tcpslice, which is the nominal tool for this. If you believe this does not solve your task, please explain in more detail.

**Comment by infrastation** [comment] 2021-08-16 17:19
Resolved, closing.

**Closed by infrastation** 2021-08-16 17:19 UTC
Labels: generic support
