### ISSUE TITLE
Problem with configure and "checking for pcap_loop"

### ISSUE THREAD

**Issue by sjvudp** [the-tcpdump-group/tcpdump#656] opened 2017-11-28 12:31 UTC
Configure for commit f085c93f fails on openSUSE 42.2 with these messages (from config.log):

```
configure:5267: checking for local pcap library
configure:5295: result: not found
configure:5347: checking for pcap-config
configure:5365: found /usr/bin/pcap-config
configure:5377: result: /usr/bin/pcap-config
configure:5592: checking for pcap_loop
configure:5592: gcc -o conftest -Wall   conftest.c -L/usr/lib64 -Wl,-rpath,/usr/lib64 -lpcap  -lnl-genl-3 -lnl-3  -ldbus-1   >&5
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lnl-genl-3
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lnl-3
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -ldbus-1
collect2: error: ld returned 1 exit status
configure:5592: $? = 1
```

Obviously these libraries (like `libdbus-1`) were not installed, but shouldn't configure check before using them? Also, why need those now? Commit 4943adfb built without.

**Comment by sjvudp** [comment] 2017-11-28 12:40
Could it be a problem of commit 768d80e1?

**Comment by sjvudp** [comment] 2017-11-28 12:54
Installing these RPM packages solved the problems:
dbus-1-devel-1.8.22-7.1.x86_64, libnl3-devel-3.2.23-4.5.x86_64

**Comment by guyharris** [comment] 2017-11-28 17:31
> Could it be a problem of commit 768d80e1?

That commit just regenerated the configure script after commit 27da449d5bdc2afc39202ddfa8d14347944c149b, which was the actual *change*.  That change came from pull request #647.

**Comment by guyharris** [comment] 2017-11-28 17:33
What do

    /usr/bin/pcap-config --cflags

    /usr/bin/pcap-config --libs

    /usr/bin/pcap-config --static --libs

print on your system?

**Comment by sjvudp** [comment] 2017-11-29 08:14
```
> /usr/bin/pcap-config --cflags
-I/usr/include
> /usr/bin/pcap-config --libs
-L/usr/lib64 -Wl,-rpath,/usr/lib64 -lpcap
> /usr/bin/pcap-config --static --libs
-L/usr/lib64 -lpcap  -lnl-genl-3 -lnl-3  -ldbus-1
```

**Comment by guyharris** [comment] 2017-11-29 20:44
>

**Comment by guyharris** [comment] 2017-11-30 02:19
This will probably be fixed by cfc4c750a225e893eeeca78eddb95fdc7125aabf.  Try the current master version.

**Comment by sjvudp** [comment] 2017-11-30 09:06
What this issue is about (in my restricted view of things): When "checking for pcap_loop", the compilation of `conftest` fails, because libraries are missing. This error seems unexpected and the whole configure aborts, _asking for a bug report_ (this one!).
In my view, _missing libraries_ should give a different kind of error message, meaning: Existence of libraries should be checked before being used, especially if the previous versions worked without them.

**Comment by guyharris** [comment] 2017-11-30 09:37
The issue is, in fact, that:

1. on most UN\*Xes, a dynamically-linked shared library  can be linked with other libraries containing routines that the first library's routines call, and a program can be linked with the first library without having to be explicitly linked with those other libraries - the run-time loader will load all the necessary shared libraries;

1. the same does not apply for *static* libraries - if you link a program with a static library that depends on other libraries, you have to link that program with those other libraries as well;

1. `pcap-config` supports a `--libs` flag that causes it to report the libraries you must link with when linking with a *dynamic* pcap library, which, due to 1 above, almost always means just `-lpcap`, no other libraries;

1. it also supports a `--static` flag that, when used in combination with `--libs``, causes it to report the libraries you must link with when linking with a *static* pcap library, which, due to 2 above, means `-lpcap` *and* all the libraries on which it depends;

1. it also supports an `--additional-libs` flag that causes it to report the libraries on which libpcap depends but *not* libpcap itself - this is intended to be used *only* when you're linking tcpdump (or some other program) with a "local" libpcap, which means a libpcap whose source directory is a subdirectory of the parent directory of the tcpdump source directory (traditionally, tcpdump let you download both libpcap and tcpdump source, build libpcap, and then build tcpdump, linking it statically with the libpcap you just built; this dates back to the days when libpcap wasn't shipped with many OSes, and if you wanted tcpdump you'd need to download libpcap and build it yourself);

1. change 27da449d5bdc2afc39202ddfa8d14347944c149b caused `--additional-libs` to be used *even if you were building with the libpcap that the system provides*, thus unnecessarily linking tcpdump with the libraries on which libpcap depends *even though you're linking with a dynamic shared libpcap library that was already linked with those libraries*, and thus unnecessarily requiring those libraries to be present;

1. the people at SuSE who produced the libpcap developer package didn't make the developer packages depend on the developer packages for the libraries on which libpcap depends.

Now, the odd thing here is that, if you had the "end user" libpcap package installed - i.e. the libpcap shared library - *that* package should depend on the "end user" packages for the libraries on which libpcap depends, so, *if* it depended on them, those libraries should already have been installed.

So, either 1) the "end user" libpcap package *doesn't* depend on the "end user" packages for those libraries, which would be a bug in openSUSE Leap 42.2, or 2) having those packages installed isn't sufficient to allow programs to be linked with those libraries, which is perhaps just an irritating complication or a misfeature of the GNU linker, or perhaps there's actually a legitimate reason why you need more than just the .so file to link with a library.

If 2) is the case, then, if you are going to link programs against libpcap, that should work, *as long as you don't try to link statically against libpcap, even though the developer package probably installs that library*, *and* as long as the tcpdump configure file doesn't get confused and think it needs to link tcpdump against those dependency libraries.

If the tcpdump configure file *does* think it needs to link against those dependency libraries even though it's linking with the dynamic libpcap library, then either the configure file is buggy or the libpcap `pcap-config` script is buggy.

In this case, it's a bug in the tcpdump configure file, and that bug should be fixed by cfc4c750a225e893eeeca78eddb95fdc7125aabf.

So the bug *isn't* that link errors due to missing libraries should be treated differently, it's that the absence of those libraries shouldn't cause the link error in the first place!

The whole purpose of the check for `pcap_loop()` - a function that should *always* be found in libpcap, rather than one that's only present in later versions of libpcap - is to make sure that we can actually link tcpdump with the libpcap that the configure script has good reason to think exists.  If it can't, then we, the tcpdump developers, have screwed up, and we want bugs to be filed so that we can fix the bug.  It is *not* a message that is intended to tell the user to do *anything* other than file a bug, so we can figure out what the underlying problem is, and either fix it ourselves or tell whoever's bug it is (e.g., the OS supplier) to fix it.

So, no, the problem isn't "the developer packages for these libraries aren't installed", the problem is "we're trying to link with those libraries when we shouldn't be doing so", and the fix isn't "the user should install the developer packages for libraries", it's "the tcpdump developers should make it unnecessary for those developer packages to be installed", and the configure script has no need to check for missing libraries, it has a need not to *care* whether the libraries are missing.

**Comment by sjvudp** [comment] 2017-11-30 12:05
Thanks for the clarification. So I can uninstall the additional packages and retry the latest master, and it should not fail. The other cases seemed useless to me anyway (Keep the libraries where the current configure does not fail, the new configure can hardly do any better. Remove the additional libraries; if configure fails, too, it would hardly be recognizable as an improvement).
A side-note: In the E-Mail copy the numbered list arrived with every item being "1."; probably a bug in github's framework.

**Comment by sjvudp** [comment] 2017-11-30 12:20
On openSUSE 42.2 (item 7): I learned that there's a package `libpcap-devel-static` in addition to `libpcap-devel`, and the former seems to have the right requirements (`bluez-devel`, `pkgconfig(libusb-1.0)`, `libnl3-devel`, `dbus-1-devel`, `libpcap-devel`). But as static libraries are generally not used, I had not installed `libpcap-devel-static`.

**Comment by guyharris** [comment] 2017-11-30 20:43
I tested this with a Leap 42.2 VM (which has a video driver, or something, that works *really poorly* with VMware Fusion).  With libpcap-devel installed but with libpcap-devel-static *not* installed, the current tip of the master branch works; if I check out the previous version of the configure file, it fails in the exact fashion you describe.

So the bug is reproducible on the VM, and the change appears to fix it.

**Comment by guyharris** [comment] 2017-11-30 20:44
> A side-note: In the E-Mail copy the numbered list arrived with every item being "1."; probably a bug in github's framework.

It displays correctly on the GitHub Web site, so, yeah, their mail generator needs to learn how to do auto-numbering.

**Closed by guyharris** 2017-11-30 20:43 UTC

**Comment by sjvudp** [comment] 2017-12-11 11:57
On openSUSE 42.2 (item 7): I learned that there's a package `libpcap-devel-static` in addition to `libpcap-devel`, and the former seems to have the right requirements (`bluez-devel`, `pkgconfig(libusb-1.0)`, `libnl3-devel`, `dbus-1-devel`, `libpcap-devel`). But as static libraries are generally not used, I had not installed `libpcap-devel-static`.
