### ISSUE TITLE
can't capture package when visite eth0 address at local machine

### ISSUE THREAD

**Issue by wangweinjcn** [the-tcpdump-group/tcpdump#847] opened 2020-04-21 08:19 UTC
tcpdump version 4.9.2
libpcap version 1.5.3
OpenSSL 1.0.2k-fips  26 Jan 2017
centos 7.4  ,eth0=192.168.1.24
I Have web server at 8009; I want to capture tcp package. when I use cmd like this:
tcpdump -i any -n port 8009  ;
if I  visite with curl http://127.0.0.1:8009 ，can capture; If I visite with curl http://192.168.1.24:8009  at this server，can get response ,but tcpdump can't capture any data.
 If I  use http://192.168.1.24:8009   at another server ,tcpdump can capture data.

**Comment by infrastation** [comment] 2021-01-07 15:39
I have tried to reproduce the problem, but everything seems to work as expected: TCP packets to a non-localhost same host local address show up with `-i any` as usual. My setup was Ubuntu 18.04, kernel 4.15.0-129-generic and current master branches of tcpdump and libpcap. Does the problem reproduce for you with the current master branch of tcpdump and libpcap?

**Comment by infrastation** [comment] 2021-01-29 18:39
Closing due to no feedback.

**Closed by infrastation** 2021-01-29 18:39 UTC
