### ISSUE TITLE
tcpdump crash on Android 6.0

### ISSUE THREAD

**Issue by zhanghl4** [the-tcpdump-group/tcpdump#536] opened 2016-08-12 06:10 UTC
Hi
Tcpdump crash on Android 6.0.
I trace tombstone log and find the crash point is a print code.

`error("%s: %s\n(%s)", device,
                    pcap_statustostr(status), cp);`

`status = pcap_activate(pd);`

```
    if (status < 0) {
        /*
         * pcap_activate() failed.
         */
        cp = pcap_geterr(pd);
        if (status == PCAP_ERROR)
            error("%s", cp);
        else if ((status == PCAP_ERROR_NO_SUCH_DEVICE ||
                  status == PCAP_ERROR_PERM_DENIED) &&
                 *cp != '\0')
            error("%s: %s\n(%s)", device,
                pcap_statustostr(status), cp);
        else
            error("%s: %s", device,
                pcap_statustostr(status));`
```

Are there any known problem about this?

thanks

**Comment by infrastation** [comment] 2016-08-12 13:56
It would help to tell the exact version of tcpdump and libpcap and the steps to reproduce, and then to hope someone with Android build environment can reproduce the issue.

**Comment by infrastation** [comment] 2016-10-12 17:10
Could it be a different way of reproducing issue #513?

**Comment by guyharris** [comment] 2017-01-17 22:34
So are you saying it crashed in the

    error("%s: %s\n(%s)", device, pcap_statustostr(status), cp);

call?

**Comment by infrastation** [comment] 2017-08-14 19:57
Closing due to no feedback.

**Closed by infrastation** 2017-08-14 19:57 UTC
Labels: bug, runtime
