### ISSUE TITLE
tcpdump with -i any shown invlida ip and bogus ipv4 in wireshark

### ISSUE THREAD

**Issue by MinpuKang** [the-tcpdump-group/tcpdump#1092] opened 2023-10-20 12:12 UTC
Hi, 
When I run tcpdump with "-i any" to capture all interface, then it shows invilda IP and then save to file and open with wireshark, it shows that bogus ipv4.

```
23:45:55.313544 eth0 P   IP8 (invalid)
23:45:55.313544 bond_port P   IP8 (invalid)
```

In wireshark:
```
Frame 5: 260 bytes on wire (2080 bits), 260 bytes captured (2080 bits)
    Encapsulation type: Linux cooked-mode capture v2 (210)
    Arrival Time: Oct 20, 2023 04:46:49.892269000 China Standard Time
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1697748409.892269000 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000752000 seconds]
    Frame Number: 5
    Frame Length: 260 bytes (2080 bits)
    Capture Length: 260 bytes (2080 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: sll:ethertype:ip]
Linux cooked capture v2
    Protocol: IPv4 (0x0800)
    Interface index: 14
    Link-layer address type: Ethernet (1)
    Packet type: Unicast to another host (3)
    Link-layer address length: 6
    Source: f0:64:81:00:45:f0
    Unused: 26f7
Internet Protocol Version 4
    1000 .... = Version: 8
        [Expert Info (Error/Protocol): Bogus IPv4 version]
            [Bogus IPv4 version]
            [Severity level: Error]
            [Group: Protocol]
```

How can I run tcpdump with correct capture?

Thanks
BRs/Minpu

**Comment by infrastation** [comment] 2023-10-20 18:21
The purpose of a packet analyser is to show accurately what is in the packet. As far as the provided output goes, both tcpdump and Wireshark seem to do that consistently and indicate an invalid value of the IP version header in a packet with IPv4 EtherType. Why this header field is invalid in this packet is a separate matter, and the best next step would be to identify the sender and to see what it is sending and why.

**Comment by guyharris** [comment] 2023-10-20 21:43
On what version of Linux (distribution and distribution version, and kernel version) are you running tcpdump?

What does `tcpdump --version` print?

**Comment by guyharris** [comment] 2023-10-20 21:44
> Why this header field is invalid in this packet is a separate matter, and the best next step would be to identify the sender and to see what it is sending and why.

Assuming what the sender sent and the machine running tcpdump received isn't getting mangled either by the Linux networking stack or by libpcap.

**Comment by guyharris** [comment] 2023-10-21 23:22
Does this also happen if you capture with `-i eth0` or `-i bond_port`?

**Comment by MinpuKang** [comment] 2023-10-23 01:46
> On what version of Linux (distribution and distribution version, and kernel version) are you running tcpdump?
> 
> What does `tcpdump --version` print?

tcpdump version 4.99.1
libpcap version 1.10.1 (with TPACKET_V3)
OpenSSL 1.1.1l  24 Aug 2021 SUSE release 150400.7.16.1
SMI-library: 0.4.8

Linux OS: Suse 15.4

**Comment by MinpuKang** [comment] 2023-10-23 01:47
> Does this also happen if you capture with `-i eth0` or `-i bond_port`?

No, with -i eth0 or -i bond_port, the printout is normal, no invalid shown, it happens only with any.

**Comment by guyharris** [comment] 2023-10-23 05:32
> No, with -i eth0 or -i bond_port, the printout is normal, no invalid shown, it happens only with any.

So probably a problem either with cooked mode in the kernel (`PF_PACKET`/`SOCK_DGRAM` rather than `PF_PACKET`/`SOCK_RAW`) or with libpcap's code for handling cooked-mode capturing.

**Comment by guyharris** [comment] 2023-10-23 05:36
> Linux OS: Suse 15.4

So that's [openSuSE Leap 15.4](https://get.opensuse.org/leap/15.4/)?

**Comment by MinpuKang** [comment] 2023-10-23 13:28
> > Linux OS: Suse 15.4
> 
> So that's [openSuSE Leap 15.4](https://get.opensuse.org/leap/15.4/)?

SUSE Linux Enterprise Server 15 SP4,

**Comment by MinpuKang** [comment] 2023-10-23 13:29
> > No, with -i eth0 or -i bond_port, the printout is normal, no invalid shown, it happens only with any.
> 
> So probably a problem either with cooked mode in the kernel (`PF_PACKET`/`SOCK_DGRAM` rather than `PF_PACKET`/`SOCK_RAW`) or with libpcap's code for handling cooked-mode capturing.

Is that possible to be fixed?

**Comment by guyharris** [comment] 2023-10-23 16:58
> Is that possible to be fixed?

If we are able to determine the cause, it might be possible for it to be fixed either in the kernel or worked around in libpcap if it's in the kernel code, and it might be possible for it to be fixed if it's in libpcap.

Unfortunately, we do not yet know the cause.

**Comment by infrastation** [comment] 2023-10-23 21:46
@MinpuKang, does the problem reproduce in a VM or SLES needs to be running on a physical host for that?

**Comment by MinpuKang** [comment] 2023-10-24 14:18
> > Is that possible to be fixed?
> 
> If we are able to determine the cause, it might be possible for it to be fixed either in the kernel or worked around in libpcap if it's in the kernel code, and it might be possible for it to be fixed if it's in libpcap.
> 
> Unfortunately, we do not yet know the cause.

understand, thank you for your answer

**Comment by MinpuKang** [comment] 2023-10-24 14:19
> @MinpuKang, does the problem reproduce in a VM or SLES needs to be running on a physical host for that?

It is a physical host.

**Comment by guyharris** [comment] 2023-10-24 18:53
Does the network eth0 is on have VLAN traffic?

In the Wireshark capture, with the "version 8" IP, what is the raw hex value of the byte for `1000 .... = Version: 8` and what is the raw hex value of the byte after it?  In particular, is the first byte 0x81 and is the byte after it 0x00?

**Comment by guyharris** [comment] 2023-10-24 22:01
> `Encapsulation type: Linux cooked-mode capture v2 (210)`

...

> `libpcap version 1.10.1 (with TPACKET_V3)`

There's a bug in libpcap 1.10.1 and at least some earlier versions that cause VLAN packets not to be properly handled by default when capturing on the "any" device.

What happens if you capture with `tcpdump -i any -y LINUX_SLL`?

**Comment by MinpuKang** [comment] 2023-10-26 11:13
> > `Encapsulation type: Linux cooked-mode capture v2 (210)`
> 
> ...
> 
> > `libpcap version 1.10.1 (with TPACKET_V3)`
> 
> There's a bug in libpcap 1.10.1 and at least some earlier versions that cause VLAN packets not to be properly handled by default when capturing on the "any" device.
> 
> What happens if you capture with `tcpdump -i any -y LINUX_SLL`?

WoW, this works well, no IP Invalid.

**Comment by MinpuKang** [comment] 2023-10-27 08:07
> > `Encapsulation type: Linux cooked-mode capture v2 (210)`
> 
> ...
> 
> > `libpcap version 1.10.1 (with TPACKET_V3)`
> 
> There's a bug in libpcap 1.10.1 and at least some earlier versions that cause VLAN packets not to be properly handled by default when capturing on the "any" device.
> 
> What happens if you capture with `tcpdump -i any -y LINUX_SLL`?

It works well, no IP invlid. Big thanks.

**Comment by guyharris** [comment] 2023-10-27 08:29
This is the-tcpdump-group/libpcap#1105, which is a lib pap bug fixed in 1.10.2.

**Closed by guyharris** 2023-10-27 08:29 UTC
Labels: generic support

**Comment by MinpuKang** [comment] 2023-10-27 12:48
> This is [the-tcpdump-group/libpcap#1105](https://github.com/the-tcpdump-group/libpcap/issues/1105), which is a libpcap bug (rather than a tcpdump bug) that is fixed in libpcap 1.10.2.

Well noted, thank you.

**Comment by drpavel777** [comment] 2024-02-01 18:04
Faced the same issue on Ubuntu 20.04.6.
tcpdump -i any -y LINUX_SLL
works well. Thanx!

**Comment by stefanlasiewski** [comment] 2024-04-13 00:33
Just wanted to add that upgrading from libpcap v1.10.1 to v1.10.4 fixed this issue for me. The new pcaps work with Wireshark 4.2.4 on macOS Sonoma/14.4.1 (Installed via Homebrew) and also TShark (Wireshark) 3.2.3 on Ubuntu 20.04.6 LTS.
