### ISSUE TITLE
i can't filtering from pcap file 

### ISSUE THREAD

**Issue by frkn4129** [the-tcpdump-group/tcpdump#961] opened 2021-11-20 12:31 UTC
Hi,
I want to filter by ip  from 15gb size pcap file.But i can't  this 
 -> tcpdump -r 123.pcap src host 19.24.243.56
return is empty

 **-Version-**
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1f  31 Mar 2020

**Comment by infrastation** [comment] 2021-11-20 12:35
How long does the command take to complete?

**Comment by frkn4129** [comment] 2021-11-20 12:37
takes a few seconds and returns empty @infrastation

**Comment by frkn4129** [comment] 2021-11-20 12:49
what could be the problem? @infrastation

**Comment by infrastation** [comment] 2021-11-20 13:01
It does not take a few seconds to read and process a 15GB file, especially given that the `-n` flag is not present, which means every IP address will be attempted to resolve to a hostname. Does the problem reproduce with libpcap 1.10.1 and tcpdump 4.99.1?

**Comment by frkn4129** [comment] 2021-11-20 13:24
@infrastation 
I did a version update but the status did not change.

I tried on 400mb file but it couldn't find src ip

**Comment by infrastation** [comment] 2021-11-20 13:27
What does the following print?
```
tcpdump -r 123.pcap -n | grep -Fc 19.24.243.56
```

**Comment by frkn4129** [comment] 2021-11-20 13:28
<pre>reading from file 123.pcap, link-type EN10MB (Ethernet)
51015
</pre>

**Comment by infrastation** [comment] 2021-11-20 13:34
So the address of interest does appear in the decoding in some capacity, but perhaps not as the source address. You need to inspect the decoding yourself and to see what the packets are when the IP address is a part of the packet. If you are looking at tunneled traffic, for example, `src host` would apply to the packet's outer header, but not to the encapsulated traffic.

**Comment by infrastation** [comment] 2021-11-20 17:26
Does this resolve your issue?

**Comment by frkn4129** [comment] 2021-11-20 17:27
no, i keep researching to fix the problem

**Comment by frkn4129** [comment] 2021-11-20 17:51
How can I see if it has a parent shell from wireshark?
@infrastation

**Comment by infrastation** [comment] 2021-11-21 14:22
If you wish to learn Wireshark, that's fine: there is both the online documentation and a few books. But that would be out of scope of this project.

As far as your comments go, the problem is not a bug in tcpdump, but that the address of interest appears not where you expect it to be. You might find the commands below helpful in understanding the composition of packet headers:
```
tcpdump -r 123.pcap -nv | grep -F -C 5 19.24.243.56 | less
```
Then you should be able to see better what pcap filter to use.

**Comment by infrastation** [comment] 2021-11-24 15:16
Closing as resolved.

**Closed by infrastation** 2021-11-24 15:16 UTC
Labels: generic support
