### ISSUE TITLE
CMake links with pkgsrc libpcap incorrectly on NetBSD 9.3

### ISSUE THREAD

**Issue by infrastation** [the-tcpdump-group/tcpdump#1008] opened 2022-09-23 23:28 UTC
NetBSD 9.3 was released not long ago, it includes a fix for the [pkgconf bug](https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=55901).  So I upgraded netbsd-amd64 to 9.3 and tried enabling the previously disabled half of the build matrix that builds with the system libpcap.

That worked for tcpslice: [build 64](https://ci.tcpdump.org/#/builders/29/builds/64) (before the reconfiguration) comprises 2 successful setups and [build 65](https://ci.tcpdump.org/#/builders/29/builds/65) (after the reconfiguration) comprises 4 successful setups.  Note that tcpslice uses Autoconf only.

The same change for tcpdump was not entirely successful, in that Autoconf worked, but CMake didn't:
```
===== SETUP 1: BUILD_LIBPCAP=no REMOTE=? CC=gcc12 CMAKE=no CRYPTO=no SMB=no =====
===== SETUP 2: BUILD_LIBPCAP=no REMOTE=? CC=gcc12 CMAKE=no CRYPTO=no SMB=yes =====
===== SETUP 3: BUILD_LIBPCAP=no REMOTE=? CC=gcc12 CMAKE=no CRYPTO=yes SMB=no =====
===== SETUP 4: BUILD_LIBPCAP=no REMOTE=? CC=gcc12 CMAKE=no CRYPTO=yes SMB=yes =====
===== SETUP 5: BUILD_LIBPCAP=no REMOTE=? CC=gcc12 CMAKE=yes CRYPTO=no SMB=no =====
$ ./build.sh
[...]
[100%] Built target tcpdump
$ make install
Consolidate compiler generated dependencies of target netdissect
[ 98%] Built target netdissect
Consolidate compiler generated dependencies of target tcpdump
[100%] Built target tcpdump
Install the project...
-- Install configuration: ""
-- Installing: /tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump
-- Set runtime path of "/tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump" to ""
-- Installing: /tmp/tcpdump_build_matrix.sgwv5fhK/man/man1/tcpdump.1
$ ldd /tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump
/tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump:
	-lpcap.0 => not found
	-lc.12 => /usr/lib/libc.so.12
$ /tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump -h
/tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump: Shared object "libpcap.so.0" not found
program finished with exit code 1
```
As it seems, before CMake installed the binary it was runnable:
```
netbsd-amd64$ ldd /tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump
/tmp/tcpdump_build_matrix.sgwv5fhK/bin/tcpdump:
        -lpcap.0 => not found
        -lc.12 => /usr/lib/libc.so.12
netbsd-amd64$ ldd build/tcpdump
build/tcpdump:
        -lpcap.0 => /usr/pkg/lib/libpcap.so.0
        -lc.12 => /usr/lib/libc.so.12
netbsd-amd64$ ./build/tcpdump --version
tcpdump version 5.0.0-PRE-GIT
libpcap version 1.10.1
netbsd-amd64$ pkgconf --libs libpcap
-Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lpcap 
netbsd-amd64$ pkgconf --cflags libpcap
-I/usr/pkg/include 
```
The CMake step that changes the runtime path seems to be the cause of this. The worker remains in the new configuration, let me know if you need assistance troubleshooting this or if the configuration should be reverted.

**Comment by guyharris** [comment] 2022-09-24 01:23
> The CMake step that changes the runtime path seems to be the cause of this.

Well, CMake's process here is... a bit contorted.

At least from my reading of the CMake source, on, I suspect, most UN\*X platforms - but not Darwin; the ~~NeXTStEP~~Darwin shared library mechanism is a bit different - CMake inserts a `file(RPATH_CHANGE ...)` command in the cmake_install.cmake file it generates in the build directory; that's the step in question,

So it's not directly something we're doing in CMakeLists.txt.

**Comment by guyharris** [comment] 2022-09-24 01:31
(BTW, it appears from [the NetBSD/amd64 page](https://wiki.netbsd.org/ports/amd64/) that "It has been tested on single-CPU and multiprocessor (SMP) Opteron configurations."  I guess those are the main AMD64 platforms out there; presumably they'll test it on more machines when it becomes a common desktop platform. :-) :-) :-) :-) :-) :-))

**Comment by guyharris** [comment] 2022-09-24 07:33
>         -lpcap.0 => /usr/pkg/lib/libpcap.so.0

What happens if you *don't* install the libpcap-1.10.1 package, and use the libpcap that comes with the OS rather than the one that comes with the package system?  Perhaps a library that's neither in /usr/lib nor /usr/local/lib confuses the "install" rule.

**Comment by guyharris** [comment] 2022-09-24 07:40
At least in my testing on my NetBSD 9.3 system, it works when I *haven't* done `sudo login libpcap` and it fails, in the fashion you describe if I *have* done `sudo install libpcap`.

I.e., I suspect the problem has to do with libraries *neither* in /usr/lib *nor* /usr/local/lib, so that the rpath has to include the directory containing the library, as it's not one of the default library directories.

**Comment by infrastation** [comment] 2022-09-24 11:59
Thank you this analysis Guy, this indeed was a user error, I got lost in the three available sources of libpcap and the three commands to query linker flags.  For reference, this is what it looks with the pkgsrc libpcap package installed (which was not installed before, but I installed it because I confused it with the OS libpcap):
```
netbsd-amd64$ pkgconf --libs libpcap
-Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lpcap 

netbsd-amd64$ pkg-config --libs libpcap
-Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lpcap 

netbsd-amd64$ pcap-config --libs
-L/usr/lib  -lpcap
```
After uninstalling the pkgsrc libpcap package tcpdump links with the OS libpcap fine, so NetBSD/AMD64 now tests the full matrix of 32 setups (see [tcpdump build 508](https://ci.tcpdump.org/#/builders/30/builds/508)).

I have added a new README file to map this space better.

**Comment by infrastation** [comment] 2022-09-24 12:03
Actually, the pkgsrc+CMake corner of this space is still broken, so let's at least say so in an open bug report until it is fixed or declared unfixable.

**Comment by guyharris** [comment] 2022-09-24 18:19
> Actually, the pkgsrc+CMake corner of this space is still broken, so let's at least say so in an open bug report until it is fixed or declared unfixable.

Yes, this *should* work, even with a libpcap neither in /usr/lib nor in /usr/local/lib.

**Comment by guyharris** [comment] 2022-09-25 19:47
At least on NetBSD - and probably on most if not all UN\*X platforms that use ELF and an SVR4-style shared library mechanism, so all the \*BSDs, most if not all Linux distributions, Solaris, and maybe 64-bit HP-UX - it appears that the linker, by default, sets an executable's RPATH to include all "extra" directories ("extra" as in "not /usr/lib or /usr/local/lib") in which it's told to search for libraries with `-L`:

     $ readelf --all tcpdump | egrep -i rpath
     0x000000000000000f (RPATH)              Library rpath: [/usr/pkg/lib]

With autotools, "make install" does not tamper with that.

With CMake, by default, the "install" target *does* tamper with that.  To quote ["RPATH handling"](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling) in the CMake wiki:

> Different RPATH settings may be required when running a program from the
build tree and when running it from its install location. If the program
links to shared libraries which have been also built in the same
project, then the RPATH needs to point to the directories in the build
tree when running the executable from the build tree, and it must not
point to the build tree anymore once the executable has been installed.
Unfortunately there is no easy and fast way to change the RPATH of an
existing executable or shared library. Since version 2.6 CMake builds
the executable with the RPATH for the build tree, and adds padding to
the RPATH if the RPATH for the install tree is longer. This way, when
installing the executable (or library), CMake can change the RPATH
inside the existing executable. Since version 2.8.12, CMake provides the
`MACOSX_RPATH` target property to enable RPATH on Mac OS X. It will be
enabled for both the build tree and install tree. If `INSTALL_NAME_DIR`
is set, RPATH will be overridden for the install tree.
> 
> ...
> 
> By default if you don't change any RPATH related settings, CMake will
link the executables and shared libraries with full RPATH to all used
libraries in the build tree. *When installing, it will clear the RPATH of
these targets so they are installed with an empty RPATH.* ...

This. Is. Not. Helpful.

What *would* be helpful would be to, when installing, remove any entries in RPATH that refer to the build path - put there if the executables you're building are dynamically linked with libraries you're building, so that the executables can find the libraries - and, if necessary, add, in their place, entries that refer to the location where those libraries are installed.

**Comment by infrastation** [comment] 2022-09-25 20:06
Thank you for looking this up. You might find it useful to know that pkgsrc contains some packages that use CMake to build and link with libraries that come from pkgsrc, for example:
```
netbsd-amd64$ ldd /usr/pkg/bin/clang
/usr/pkg/bin/clang:
        -lpthread.1 => /usr/lib/libpthread.so.1
        -lc.12 => /usr/lib/libc.so.12
        -lclang-cpp.13 => /usr/pkg/lib/libclang-cpp.so.13
        -lLLVM-13 => /usr/pkg/lib/libLLVM-13.so
        -ledit.3 => /usr/lib/libedit.so.3
        -lterminfo.1 => /usr/lib/libterminfo.so.1
        -lrt.1 => /usr/lib/librt.so.1
        -lexecinfo.0 => /usr/lib/libexecinfo.so.0
        -lelf.2 => /usr/lib/libelf.so.2
        -lgcc_s.1 => /usr/lib/libgcc_s.so.1
        -lz.1 => /usr/lib/libz.so.1
        -lxml2.2 => /usr/pkg/lib/libxml2.so.2
        -llzma.2 => /usr/lib/liblzma.so.2
        -lm.0 => /usr/lib/libm.so.0
        -lstdc++.9 => /usr/lib/libstdc++.so.9
```
Since tcpdump uses the same CMake package from pkgsrc, it looks like pkgsrc found a way not to break RPATH. (It does not necessarily mean the solution is a good thing to copy, but it helps to know it exists.)

**Comment by guyharris** [comment] 2022-09-26 00:27
I think dcfed11c0baaa95085b51772439f67f09704402c should fix this.

Would it make sense to have *three* items in the matrix for NetBSD - build with current libpcap from source, build with the system libpcap, and build with the pkgsrc libpcap?

**Comment by infrastation** [comment] 2022-09-26 08:01
Thank you! Yes, it would, if the build system(s) had means to take such a request without modifying the source.  If that does not work, it might be possible to test {local, system} on one NetBSD worker and {local, pkgsrc} on another by aliasing `pcap-config` or `pkg-config` to `false` (or some such).

**Comment by guyharris** [comment] 2022-09-26 08:41
So this seemed to work in my testing on a NetBSD 9.3 VM.  Closing.

(The issue is, I suspect, more than just a NetBSD issue; other OSes with the ELF/SVR4-style shared library mechanism also require setting the run-time library path, at least with a simple test I did with a trivial pcap-based program that just prints the result of `pcap_lib_version()`.  If the version of the shared library with which the program is linked matches that of the version in /usr/lib, however, the only symptoms would be those resulting from using a different shared library version, rather than a failure to find the shared library.)

**Closed by guyharris** 2022-09-26 08:41 UTC
Labels: bug, compiling

**Comment by infrastation** [comment] 2022-10-30 13:37
To follow up on having the pkgsrc libpcap case in CI, after a while I realized that {local, system} on one NetBSD worker and {local, pkgsrc} on another was exactly the arrangement that I got by accident when making this bug report because installing the pkgsrc version makes `pkg-config` recognize libpcap, and tcpdump build process tries `pkg-config` before `pcap-config` and is satisfied with the first method that works (this behaviour is consistent between Autoconf and CMake).

So netbsd-amd64 has the pkgsrc libpcap package installed again and that makes the CMake RPATH bug fix above tested on NetBSD. If in future it becomes necessary to test both system libpcap and pkgsrc libpcap on the *same* NetBSD host, the likely means would be through additional complication in `build_matrix.sh`.

The NetBSD-specific README now says pkgsrc libpcap is expected to work.
