### ISSUE TITLE
Catch "tcpdump: bad dump file format" for "make check"

### ISSUE THREAD

**Issue by sjvudp** [the-tcpdump-group/tcpdump#633] opened 2017-09-12 15:18 UTC
When doing a "`make check`" after building the master branch, quite a lot of tests fail with the logs just stating **exit code 1**. When running `tcpdump` manually, I see a "`tcpdump: bad dump file format`".
Probably cause is an older libpcap-devel, namely 0.9.8 (1.8.1 seems OK).
So I suggest for "`make check`":

- Detect the "`tcpdump: bad dump file format`" problem, i.e. add the error message to the output of tcpdump

- Better: Skip the tests with incompatible pcap file format. This may require to teach "`file`" about the pcap format; currently it says it's just "`data`".

- convert incompatible pcap files to compatible ones; preferrably providing a utility that can do that.

Example of an incompatible pcap file is `tests/bgp-shutdown-communication.pcap`.

I have a quick-and-dirty patch suggestion:

    From dc0a3cb975f6f371c913b5288819b7f3abc348fb Mon Sep 17 00:00:00 2001
    From: Ulrich Windl <Ulrich.Windl@RZ.Uni-Regensburg.DE>
    Date: Tue, 12 Sep 2017 17:08:46 +0200
    Subject: [PATCH] tests/TESTonce: More verbose failure message

    Add the reason for not executing a test and the status if the command
    exited with a non-zero status.
    ---
     tests/TESTonce | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)
    
    diff --git a/tests/TESTonce b/tests/TESTonce
    index 7026624..3be31f9 100755
    --- a/tests/TESTonce
    +++ b/tests/TESTonce
    @@ -40,7 +40,7 @@ if($r == 0) {
       unlink "DIFF/$output.diff";
       exit 0;
     }
    -printf "    %-35s: TEST FAILED", $name;
    +printf "    %-35s: TEST FAILED(%s)", $name, $r == -1 ? $! : "exit $?";
     open FOUT, '>>failure-outputs.txt';
     printf FOUT "Failed test: $name\n\n";
     close FOUT;
    -- 
    1.7.12.4

**Comment by guyharris** [comment] 2017-09-13 03:44
> Better: Skip the tests with incompatible pcap file format. This may require to teach "`file`" about the pcap format; currently it says it's just "`data`".

Nope:

    $ file tests/bgp-shutdown-communication.pcap
    tests/bgp-shutdown-communication.pcap: pcap-ng capture file - version 1.0

You just need a newer version of `file`.

> convert incompatible pcap files to compatible ones; preferrably providing a utility that can do that.

If you have a sufficiently recent version of libpcap (1.0 or later), the utility to do that is called "tcpdump":

    $ tcpdump -r tests/bgp-shutdown-communication.pcap -w /tmp/bgp-shutdown-communication.pcap
    reading from file tests/bgp-shutdown-communication.pcap, link-type EN10MB (Ethernet)
    $ file /tmp/bgp-shutdown-communication.pcap 
    /tmp/bgp-shutdown-communication.pcap: tcpdump capture file (little-endian) - version 2.4 (Ethernet, capture length 262144)

Unfortunately, the "capture length 262144" is another problem, as older versions of libpcap might reject that snapshot length as being too large.

> I have a quick-and-dirty patch suggestion:

Committed as 071190f7a96d273fe79dc6f3ca12153d8db1de00.

**Comment by sjvudp** [comment] 2017-09-14 07:02
What version of file are you using? With `file-5.19-6.53.x86_64` (openSUSE) here the file above is still recognized as "data", while others are recognized. E.g.:
```
tests/rsvp-infinite-loop.pcap:                tcpdump capture file (little-endian) - version 2.4 (Linux "cooked", capture length 96)
tests/bgp-shutdown-communication.pcap:        data
```

**Comment by infrastation** [comment] 2017-09-14 08:33
```
$ file tests/bgp-shutdown-communication.pcap
tests/bgp-shutdown-communication.pcap: pcap-ng capture file - version 1.0
$ file --version
file-5.25
magic file from /etc/magic:/usr/share/misc/magic
[...]
Version: 1:5.25-2ubuntu1
```
Though generally this cannot be relied upon on a random build host. Would it be more helpful to have it stated somewhere that the tests must pass when tcpdump is built with the latest libpcap and may fail with older versions?

**Comment by sjvudp** [comment] 2017-09-14 10:49
Maybe a primitive C target using libpcap could be built that just tries to extract a packet from the given file; if it fails (exit != 0), either the file is broken, or libpcap cannot read it. It could be used in the test scripts. Maybe even some verbose diagnostic could be given.
BTW: As TESTonce uses Perl, it seems to be a good idea to integrate TESTrun.sh and TESTonce into once Perl script for more performance. The it would be rather simple to run any subset of the existing tests (TESTrun.sh can only pick one test now).

**Comment by guyharris** [comment] 2017-09-14 19:47
> What version of file are you using?

    $ file --version
    file-5.25
    magic file from /usr/share/file/magic

from macOS Sierra.  [The Ian Darwin file command](http://www.darwinsys.com/file/) has had support for pcapng files in its magic file for several releases, and I think that's the file command that most Linux distributions use; are you using one of those "enterprise" distributions with software that's several years old?

**Comment by guyharris** [comment] 2017-09-14 19:55
For the current files that either are pcapng files or have snapshot lengths that are too large for older versions of libpcap, we might be able to use tcpdump or Wireshark's editcap to 1) convert them to pcap files and 2) make sure the snapshot length is <= 65535, as long as 1) all interfaces in the capture file have the same link-layer header type and 2) no packet has a captured length > 65535.

In order to continue to support `make check` with older versions of libpcap, we'd have to establish a policy that test files must fit those criteria.

**Comment by sjvudp** [comment] 2017-09-14 20:18
My `file` utility is older than 5.25, and yes, I'm using an enterprise distribution (SLES11 SP4). Maybe you want to read [[Bug 1058638] file utility should recognize more pcap files](http://bugzilla.suse.com/show_bug.cgi?id=1058638).

Maybe in a first step it would be helpful to switch to "`TEST SKIPPED`" if the pcap file cannot be processed. Then multiple users and developers will become aware of the problem.

**Comment by infrastation** [comment] 2017-09-16 21:58
The matter with tests is that if a test fails you cannot imply it had a good reason to fail. If you want to skip certain tests because they don't work with older libpcap versions (and that is extra work because anything older than the current master branch is notably less interesting), it will work to put such tests to a custom shell script like `lmp-v.sh`, which will differentiate based on libpcap version (which you can get from `tcpdump --version`) and either run the test normally or skip it with a reason.

**Comment by infrastation** [comment] 2017-09-20 13:58
The proposed patch has been committed to the master branch, thus the issue is closed. Feel free to use the tcpdump-workers mailing list for any ongoing discussion.

**Closed by infrastation** 2017-09-20 13:58 UTC
