### ISSUE TITLE
Filters not working with pcap including VLAN (802.1Q)

### ISSUE THREAD

**Issue by awgn** [the-tcpdump-group/tcpdump#900] opened 2021-01-13 12:39 UTC
Tcpdump is not able to filter packets in pcap files when ethertype 802.1Q header is present:

$ tcpdump --version
tcpdump version 4.99.0
libpcap version 1.10.0
OpenSSL 1.1.1i  8 Dec 2020

$ tcpdump -n -e -r ./test.pcap
reading from file ./test.pcap, link-type EN10MB (Ethernet), snapshot length 1500
12:23:40.763084 xx:xx:d4:82:38:24 > xx:xx:xx:43:66:40, ethertype 802.1Q (0x8100), length 76: vlan 31, p 0, ethertype IPv4 (0x0800), 10.11.27.62.53 > 10.15110.19.45002: 8089 Refused- 0/0/0 (30)
...

$ tcpdump -n -e -r ./test.pcap ip
reading from file ./test.pcap, link-type EN10MB (Ethernet), snapshot length 1500
$ (no packet is shown)

Most probably the same issue is present for IPv6 packets.

**Comment by guyharris** [comment] 2021-01-13 12:47
You have to do `vlan and ip` (or `vlan and ip6`).

**Comment by awgn** [comment] 2021-01-13 12:53
If you specify the ip filter you probably want all IPv4 packets, regardless the presence of the vlan, imo.

**Comment by guyharris** [comment] 2021-01-13 13:14
> If you specify the ip filter you probably want all IPv4 packets, regardless the presence of the vlan, imo.

Then you need `ip or (vlan and ip)`.

**Comment by infrastation** [comment] 2021-01-30 13:26
For reference, the [pcap-filter man page](https://www.tcpdump.org/manpages/pcap-filter.7.html) covers VLAN syntax in more detail. Closing as resolved.

**Closed by infrastation** 2021-01-30 13:26 UTC
Labels: generic support

**Comment by durkovic** [comment] 2021-05-18 17:47
I think this issue was not described in required detail.

The problem is, that vlan keyword is NOT needed, when tcpdump reads from physical interface, "ip" is enough.

But when it reads from pcap file, filters unexpectedly stop working unless you use "vlan and ip". This is very confusing. 

@infrastation could you please reopen this issue?

**Comment by infrastation** [comment] 2021-11-29 22:43
Hmm, the last statement is true: `tcpdump -pni eno1 -ev ip` on a Linux PC clearly shows both packets with EthertType 0x0800 (IPv4) and 0x8100 (802.1Q). The same stands for ICMP. In both cases only received tagged packets show up for no apparent reason. This reminds me of tests I recently did for another similar issue, which I cannot find right now. This also vaguely reminds me of some Linux VLAN specifics.

**Comment by infrastation** [comment] 2021-12-18 16:47
For posterity, there is now a [FAQ entry](https://www.tcpdump.org/faq.html#q13) about this.
