### ISSUE TITLE
Problem tcpdump does not show actual traffic

### ISSUE THREAD

**Issue by FrancoisLAGANT** [the-tcpdump-group/tcpdump#1040] opened 2023-03-29 13:47 UTC
Hello,

I have a problem on tcpdump where it appears to me:
Namely that I do not have GRE as traffic but only TLS
```
tcpdump -s0 -nni eno1 -c10
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eno1, link-type EN10MB (Ethernet), capture size 262144 bytes
15:02:14.680015 IP 36.253.118.188 > 36.50.146.224: GREv0, length 1458: gre-proto-0x88be
15:02:14.680016 IP 36.253.118.188 > 36.50.146.224: GREv0, length 74: gre-proto-0x88be
15:02:14.680018 IP 36.253.118.188 > 36.50.146.224: GREv0, length 406: gre-proto-0x88be
15:02:14.680019 IP 36.253.118.188 > 36.50.146.224: GREv0, length 74: gre-proto-0x88be
15:02:14.680020 IP 36.253.118.188 > 36.50.146.224: GREv0, length 74: gre-proto-0x88be
15:02:14.680021 IP 36.253.118.188 > 36.50.146.224: GREv0, length 1137: gre-proto-0x88be
15:02:14.680022 IP 36.253.118.188 > 36.50.146.224: GREv0, length 74: gre-proto-0x88be
15:02:14.680028 IP 0.0.0.100 > 34.41.181.216: GREv0, length 74: gre-proto-0x88be
15:02:14.680030 IP 36.253.118.188 > 36.50.146.224: GREv0, length 74: gre-proto-0x88be
15:02:14.680031 IP 36.253.118.188 > 36.50.146.224: GREv0, length 74: gre-proto-0x88be
10 packets captured
1912 packets received by filter
1870 packets dropped by kernel
```
Whereas if I add the -w file.pcap the dump is correct and shows normal traffic fine or I don't have GRE.
Also with the -w option there is no drop package:
```
tcpdump -s0 -nni eno1 -c100 -w test.pcap
dropped privs to tcpdump
tcpdump: listening on eno1, link-type EN10MB (Ethernet), capture size 262144 bytes
100 packets captured
1024 packets received by filter
0 packets dropped by kernel
```

Also if I use tshark I have no problem.
```
tshark -s0 -nni eno1 -c10
Running as user "root" and group "root". This could be dangerous.
Capturing on 'eno1'
    1 0.000000000 x.x.x.x→ x.x.x.x TCP 108 62921 → 80 [ACK] Seq=1 Ack=1 Win=65535 Len=0 TSval=765071721 TSecr=383057921
    2 0.000001817 x.x.x.x → x.x.x.x TCP 108 60062 → 443 [ACK] Seq=1 Ack=1 Win=1134 Len=0 TSval=39410851 TSecr=765071690
    3 0.000002431 x.x.x.x → x.x.x.x TCP 108 35349 → 443 [ACK] Seq=1 Ack=1 Win=1223 Len=0 TSval=729933998 TSecr=765071716
    4 0.000003579 x.x.x.x → x.x.x.x TCP 108 40920 → 443 [ACK] Seq=1 Ack=1 Win=1003 Len=0 TSval=1079598052 TSecr=765071708
    5 0.000005052 x.x.x.x → x.x.x.x SSL 121 Continuation Data
    6 0.000023197 x.x.x.x → x.x.x.x SSL 593 Continuation Data
    7 0.000024064 x.x.x.x → x.x.x.x SSL 424 Continuation Data
    8 0.000024751 x.x.x.x → x.x.x.x SSL 1129 [TCP Previous segment not captured] , Continuation Data
    9 0.000025423 x.x.x.x → x.x.x.x SSL 137 [TCP Previous segment not captured] , Continuation Data
   10 0.000025957 x.x.x.x → x.x.x.x HTTP 505 HTTP/1.1 200 OK  (text/html)
10 packets captured
```
redhat 8.7
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1k  FIPS 25 Mar 2021

Can you help me solve my problem.

**Comment by infrastation** [comment] 2023-03-29 17:38
4.9.3 and 1.9.1 are rather old, so this problem might have been fixed in later versions. What are the most recent tcpdump and libpcap releases that reproduce the problem on this system?

**Comment by FrancoisLAGANT** [comment] 2023-03-30 07:47
I am already in the latest version that the repository offers me.
How can I find a solution?
On another identical server installed much earlier in redhat 7.8
tcpdump version 4.9.2
libpcap version 1.5.3
OpenSSL 1.0.2k-fips 26 Jan 2017
it works perfectly fine.

**Comment by guyharris** [comment] 2023-03-30 08:18
> `gre-proto-0x88be`

0x88BE is an Ethernet type value assigned to Cisco.  The set of GRE protocol types is mostly shared with the set of Ethernet protocol types, and a GRE type of 0x88BE appears to be used by Cisco for their ERSPAN (Encapsulated Remote Switched Port Analyzer) protocol.  See, for example, https://study-ccnp.com/erspan-encapsulated-remote-span-explained/, https://community.cisco.com/t5/networking-knowledge-base/understanding-span-rspan-and-erspan/ta-p/3144951, https://packetpushers.net/erspan-new-favorite-packet-capturing-trick/, and other pages found by a web search for ERSPAN.

To quote some comments in the Wireshark ERSPAN dissector:

> Protocol Spec:  
>   https://tools.ietf.org/html/draft-foschiano-erspan-03
> 
> For ERSPAN packets, the "protocol type" field value in the GRE header
> is 0x88BE (types I and II) or 0x22EB (type III).
> 
> For 0x88BE, if the GRE header doesn't have the "sequence number present"
> flag set, it's type I, with no ERSPAN header, otherwise it has an
> ERSPAN header (it's supposed to be type II, but we look at the version
> in the ERSPAN header; should we report an error if it's not version 1?).
> 
> For 0x22EB, it always has an ERSPAN header (it's supposed to be type III,
> but we look at the version in the ERSPAN header; should we report an
> error if it's not version 2?).

> Whereas if I add the -w file.pcap the dump is correct and shows normal traffic fine or I don't have GRE.

If you add `-w file.pcap`, tcpdump doesn't show *anything*.  Perhaps if you then read that dump with Wireshark or TShark, you see the traffic because Wireshark/TShark have a dissector for ERSPAN; what happens if you read that dump with *tcpdump*?  If so, I suspect it will show the same "gre-proto-0x88be" stuff that it did when you did a capture without `-w`.

> Also if I use tshark I have no problem.

That's because, as noted, Wireshark/TShark have a dissector for ERSPAN, so it's dissecting the packets encapsulated in ERSPAN.  Tcpdump does *not* dissect ERSPAN, so it just shows it as being GRE traffic with an unknown GRE type of 0x88be.

> On another identical server installed much earlier in redhat 7.8 ... it works perfectly fine.

Perhaps, for some reason, in that case the traffic you're capturing isn't ERSPAN traffic.

> How can I find a solution?

By either:

1. Finding a version of tcpdump that dissects ERSPAN.
2. Finding somebody to modify tcpdump to dissect ERSPAN and then using that modified version of tcpdump;
3. Saving the tcpdump capture and reading it with Wireshark/TShark or some other sniffer that dissects ERSPAN.

I'll see if I have any ERSPAN captures and, if so, look at adding ERSPAN support to tcpdump.  Note, however, that the versions of tcpdump supplied with operating systems won't dissect ERSPAN until we release a version of tcpdump with that support and the OS suppliers pick up that version - and you have an OS version with that version of tcpdump in it.  Otherwise, you'd have to compile tcpdump from source once ERSPAN support has been added, and use the version you compiled.

**Comment by infrastation** [comment] 2023-03-30 19:16
> These addresses and packet types can be ignored.

Dear people from future. Before the Internet collapsed, we were given signs this was going to happen. We ignored them because somebody wrote we could.

**Comment by infrastation** [comment] 2023-06-04 11:18
So, the vendor's product and support problems aside, as far as tcpdump scope goes, it would be nice to implement complete ERSPAN decoding, which may or may not eventually happen. Meanwhile let me suggest to improve the identification aspect of ERSPAN by making the following change:
```diff
diff --git a/ethertype.h b/ethertype.h
index 8b71b302..0da843d8 100644
--- a/ethertype.h
+++ b/ethertype.h
@@ -215,5 +215,11 @@
 #ifndef        ETHERTYPE_ARISTA
 #define        ETHERTYPE_ARISTA        0xd28b /*  Arista Networks vendor specific EtherType */
 #endif
+#ifndef        ETHERTYPE_ERSPAN_1_2
+#define        ETHERTYPE_ERSPAN_1_2    0x88be
+#endif
+#ifndef        ETHERTYPE_ERSPAN_3
+#define        ETHERTYPE_ERSPAN_3      0x22eb
+#endif
 
 extern const struct tok ethertype_values[];
diff --git a/print-gre.c b/print-gre.c
index 25c6ac2f..4ac186b0 100644
--- a/print-gre.c
+++ b/print-gre.c
@@ -308,6 +308,12 @@ gre_print_0(netdissect_options *ndo, const u_char *bp, u_int length)
        case ETHERTYPE_NSH:
                nsh_print(ndo, bp, len);
                break;
+       case ETHERTYPE_ERSPAN_1_2:
+               ND_PRINT("ERSPAN type %s", flags & GRE_SP ? "II" : "I");
+               break;
+       case ETHERTYPE_ERSPAN_3:
+               ND_PRINT("ERSPAN type III");
+               break;
        case GRE_CDP:
                cdp_print(ndo, bp, len);
                break;
```
This should make it easier for users to see the unexpected encapsulation. Stripping ERSPAN headers from a `.pcap` file (or a pipe) would not be difficult using one of the several tools available ([example](https://staff.washington.edu/corey/gulp/)).

**Closed** 2023-06-07 22:20 UTC
Labels: generic support, runtime

**Comment by guyharris** [comment] 2023-06-07 22:21
I took an ERSPAN dissector from the OpenBSD tcpdump and added the two additional GRE types to print-gre.c.

**Comment by infrastation** [comment] 2023-06-08 21:24
Thank you!

**Comment by guyharris** [comment] 2023-06-09 06:59
> Thank you!

And thank the OpenBSD folks for writing the ERSPAN stuff on which it's based.
