### ISSUE TITLE
tcpdump drops packets in default setup

### ISSUE THREAD

**Issue by msehnout** [the-tcpdump-group/tcpdump#600] opened 2017-04-24 08:20 UTC
When I try to run this simple test, tcpdump drops packets:

1. Start a server: `# nc -l 7788`
2. Run tcpdump: `# tcpdump -i eth0 port 7788`
3. Run client app: `# echo hello | nc <serverName> 7788`

**Result:**
7 packets captured
8 packets received by filter
1 packet dropped by kernel

**Workaround:** use smaller snaplen or bigger buffer size:
```
# tcpdump -s 65535 -i eth0 port 55555 > /dev/null
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
^C8 packets captured
8 packets received by filter
0 packets dropped by kernel
```

**Environment:** Fedora 25 with upstream tcpdump

Shouldn't tcpdump use bigger buffer size by default to prevent such behavior?

**Comment by guyharris** [comment] 2017-04-24 09:57
Which version of libpcap is being used (`tcpdump -v` will report that)?

**Comment by msehnout** [comment] 2017-04-24 10:12
```
[user@localhost tcpdump]$ ./tcpdump -h
tcpdump version 4.10.0-PRE-GIT_2017_04_21
libpcap version 1.7.4
OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by guyharris** [comment] 2017-05-13 02:33
So presumably both "dropping with the default snapshot" and "not dropping with a snapshot of 65535" are reproducible?  For TPACKET_V3, the snapshot length doesn't change the way the ring buffer is set up, and, for Ethernet, 65535 is much larger than the largest possible packet, so it shouldn't be the case that you're dropping fewer packets because it's only capturing the first 65535 bytes of the packet.  Fedora 25 should be running a kernel with TPACKET_V3 support - that's been there since some 3.x kernel - so it shouldn't be using TPACKET_V2.

(Or is this some virtual-machine thing, so that "eth0" isn't a real Ethernet, and ends up sending Really Big Packets, > 65535 bytes in length?)

**Comment by msehnout** [comment] 2017-05-16 10:11
> Fedora 25 should be running a kernel with TPACKET_V3 support - that's been there since some 3.x  kernel - so it shouldn't be using TPACKET_V2.

ok, I'll try it with TPACKET_V3 support and let you know. Fedora is still using TPACKET_V2 because of some issues few years ago.

**Comment by infrastation** [comment] 2017-05-16 13:13
Would it be easier to troubleshoot if `tcpdump --version` told which kernel interface is being used?

**Comment by guyharris** [comment] 2017-05-16 18:25
> Would it be easier to troubleshoot if `tcpdump --version` told which kernel interface is being used?

Probably.  Wireshark's `--version` dumps a lot of information.  We could indicate which kernel interfaces are *supported by the libpcap code* in the results of `pcap_lib_version()`.  Now, if the *kernel* doesn't support TPACKET_V3, we obviously won't use it, but we can ask for the `uname -sr` output.

**Comment by guyharris** [comment] 2017-05-16 19:20
I've added more version information in the-tcpdump-group/libpcap#600; that obviously won't help with OSes supplying releases prior to 1.9.0 (after 1.9.0 comes out), but at least with newer OS releases it might help.

**Comment by guyharris** [comment] 2017-05-17 02:24
TPACKET_V2 (and TPACKET_V1, which only differs from TPACKET_V2 in a minor way that causes problems with a 64-bit kernel and 32-bit userland; TPACKET_V2 fixed that) aren't the best mechanisms for packet capture, as they require a ring of *fixed-length* buffers, one per packet, so the buffer needs to be large enough for the maximum-size packet and, if a smaller packet arrives, the rest of the memory for the buffer is wasted.  TPACKET_V3 packs as many packets as it can in a buffer.

Linux does *not* make it easy for userland code to find a guaranteed maximum packet size, so libpcap picks values that can be larger than necessary.  Change 5409b7ab378be997c0d26ba41a6ca18795e0b581 improves the calculation so it's not as big, but TPACKET_V3 is still preferred.

**Comment by msehnout** [comment] 2017-05-18 08:00
This is the output of wireshark and tcpdump version:
```txt
~/d/g/tcpdump (master|…) $ ./tcpdump --version 
tcpdump version 4.10.0-PRE-GIT_2017_04_25
libpcap version 1.7.4
OpenSSL 1.0.2k-fips  26 Jan 2017
SMI-library: 0.4.8
~/d/g/tcpdump (master|…) $ wireshark --version 
Wireshark 2.2.6 (wireshark-2.2.6)

Copyright 1998-2017 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with GTK+ 3.22.11, with Cairo 1.14.8, with Pango 1.40.4, with
libpcap, with POSIX capabilities (Linux), with libnl 3, with GLib 2.50.3, with
zlib 1.2.8, with SMI 0.4.8, with c-ares 1.12.0, without Lua, with GnuTLS 3.5.11,
with Gcrypt 1.6.6, with MIT Kerberos, with GeoIP, with PortAudio V19-devel
(built Feb  5 2016 01:14:30), without AirPcap.

Running on Linux 4.10.14-200.fc25.x86_64, with locale en_US.UTF-8, with libpcap
version 1.7.4, with GnuTLS 3.5.11, with Gcrypt 1.6.6, with zlib 1.2.8.
Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (with SSE4.2)

Built using gcc 6.3.1 20161221 (Red Hat 6.3.1-1).
```

And we also use this patch in Fedora for libpcap:
http://pkgs.fedoraproject.org/cgit/rpms/libpcap.git/tree/0004-pcap-linux-don-t-use-TPACKETV3-for-memory-mmapped-ca.patch

**Comment by guyharris** [comment] 2017-05-18 08:22
As a rationale for not using TPACKET_V3, they mention [libpcap issue 380](https://github.com/the-tcpdump-group/libpcap/issues/380) and [libpcap issue 364](https://github.com/the-tcpdump-group/libpcap/issues/364), *both* of which are fixed by *kernel* patches from Dan Collins.  As issue 380 notes, that fix is in the 3.19 kernel.

**Comment by msehnout** [comment] 2017-05-18 12:24
Just to be sure, how do I know that I'm actually running TPACKET_V3? Is it the number "[2]" in this syscall?

```txt
# filtered from strace output of tcpdump
setsockopt(3, SOL_PACKET, PACKET_VERSION, [2], 4) = 0
```

**Comment by guyharris** [comment] 2017-05-19 01:39
> Just to be sure, how do I know that I'm actually running TPACKET_V3? Is it the number "[2]" in this syscall?

Yes.  The definition of the versions in the Linux header files is:

    enum tpacket_versions {
            TPACKET_V1,
            TPACKET_V2,
            TPACKET_V3
    };

so `TPACKET_V1` is 0, `TPACKET_V2` is 1, and `TPACKET_V3` is 2.

**Comment by mcr** [comment] 2019-04-16 18:25
Please re-open if this is still an issue.

**Closed by mcr** 2019-04-16 18:25 UTC
