### ISSUE TITLE
The tcpdump man page appears not to document one of the TCP flags

### ISSUE THREAD

**Issue by YangQing1989** [the-tcpdump-group/tcpdump#1069] opened 2023-07-28 07:16 UTC
https://www.tcpdump.org/manpages/tcpdump.1.html

```
|  HL   | rsvd  |C|E|U|A|P|R|S|F|        window size            |
```
I think there is a missing TCP flag：**Accurate ECN**

**Comment by infrastation** [comment] 2023-07-28 20:39
Thank you for bringing this up, let's treat this as a duplicate of #999.

**Closed by infrastation** 2023-07-28 20:39 UTC

**Comment by guyharris** [comment] 2024-05-16 17:26
Duplicate of #999
