### ISSUE TITLE
crypto.sh test case corrupts .passed/.failed counters when compiled without crypto

### ISSUE THREAD

**Issue by Sashan** [the-tcpdump-group/tcpdump#648] opened 2017-11-15 14:39 UTC
Solaris ships tcpdump without crypto support (--without-crypto). When running target make check
we see errors as follows:
```
expr: syntax error
    bgp-aigp-oobr-nossl                : passed
expr: syntax error
    isis-seg-fault-1-v                 : TEST SKIPPED (compiler is not GCC)
    lmp-v                              : TEST SKIPPED (compiler is not GCC)
```
It has turned out the bug is caused by tests/crypto.sh, which fails to properly initialize
passed/failed local variables, when running 'crypto not available' branch. patch below
fixes the issue:
```
--- tcpdump-4.9.2/tests/crypto.sh       2017-09-04 01:17:14.000000000 +0200
+++ tcpdump-4.9.2.fixed/tests/crypto.sh 2017-11-15 15:19:59.351099113 +0100
@@ -4,10 +4,10 @@
 
 # Only attempt OpenSSL-specific tests when compiled with the library.
 
+passed=`cat .passed`
+failed=`cat .failed`
 if grep '^#define HAVE_LIBCRYPTO 1$' ../config.h >/dev/null
 then
-       passed=`cat .passed`
-       failed=`cat .failed`
        if ./TESTonce esp1 02-sunrise-sunset-esp.pcap esp1.out '-E "0x12345678@192.1.2.45 3des-cbc-hmac96:0x4043434545464649494a4a4c4c4f4f515152525454575758"'
        then
                passed=`expr $passed + 1`
```

**Comment by infrastation** [comment] 2017-11-15 16:22
Good spot, I had seen this bug before but could not reproduce it.

**Comment by infrastation** [comment] 2018-01-31 22:01
This bug was fixed in the master branch 2 months before this bug report with commit cd246d1, so nothing remains to be done. Thanks for the report anyway!

**Closed by infrastation** 2018-01-31 22:01 UTC
