### ISSUE TITLE
Out of bound read in relts_print

### ISSUE THREAD

**Issue by yyyyxf** [the-tcpdump-group/tcpdump#571] opened 2016-12-06 01:27 UTC
Git HEAD:  4abe278  
tcpdump -r $file

[1.txt](https://github.com/the-tcpdump-group/tcpdump/files/632731/1.txt)

==13965== Invalid read of size 4
==13965==    at 0x64FFF0: relts_print (util-print.c:362)
==13965==    by 0x544166: lwres_print (print-lwres.c:545)
==13965==    by 0x4DACAC: ip_print_demux (print-ip.c:383)
==13965==    by 0x4D7F88: ip_print (print-ip.c:648)
==13965==    by 0x4A0A05: ethertype_print (print-ether.c:325)
==13965==    by 0x4A17F8: ether_print.part.0 (print-ether.c:229)
==13965==    by 0x4281AA: pretty_print_packet (print.c:339)
==13965==    by 0x4122B8: print_packet (tcpdump.c:2492)
==13965==    by 0x4E58AC3: ??? (in /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4)
==13965==    by 0x4E491CE: pcap_loop (in /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4)
==13965==    by 0x40C32D: main (tcpdump.c:1996)

**Comment by infrastation** [comment] 2016-12-06 21:55
This is a known problem and it is being looked into, thank you for the report.

**Comment by fgeek** [comment] 2016-12-10 01:04
Looks like duplicate of #496 issue.

**Comment by infrastation** [comment] 2017-01-11 17:32
Yes, that is correct.

**Closed by infrastation** 2017-01-11 17:32 UTC

**Comment by infrastation** [comment] 2017-02-02 13:40
Please send any future security reports to security@tcpdump.org.

**Comment by guyharris** [comment] 2024-05-16 17:40
Duplicate of #496
