### ISSUE TITLE
pcap-invalid-version-2 & pcap-ng-invalid-vers-2 fails 'make check'

### ISSUE THREAD

**Issue by bijalthanawala** [the-tcpdump-group/tcpdump#532] opened 2016-07-16 20:45 UTC
I am trying to make my first contribution (pull request) to this project (fix for https://github.com/the-tcpdump-group/tcpdump/issues/522), and I noticed the requirement for 'make check' to pass before making the pull request.

On running 'make check', two test-cases fails on a **fresh** clone.
After investigating within my capacity, I am posing this question as an issue, whether this is by design or any dependency missing on my **Fedora 23** system ?

```
Failed test: pcap-invalid-version-2

1c1
< EXIT CODE 00000100

---
> IP6 fe80::b299:28ff:fec8:d646.6696 > ff02::1:6.6696: babel 2 (424) hello update/id request tspc hmac hmac hmac hmac hmac hmac hmac hmac


Failed test: pcap-ng-invalid-vers-2

1c1
< EXIT CODE 00000100

---
> IP6 fe80::20c:29ff:fe9e:c1b2 > ff02::5: OSPFv3, Hello, length 88


Makefile:433: recipe for target 'check' failed

```

```
$ rpm -qi libpcap
Name        : libpcap
Epoch       : 14
Version     : 1.7.4
Release     : 1.fc23
Architecture: x86_64
Install Date: Fri 30 Oct 2015 08:22:13 AM AEDT
Group       : Development/Libraries
Size        : 336770
License     : BSD with advertising
Signature   : RSA/SHA256, Tue 30 Jun 2015 03:21:39 AM AEST, Key ID 32474cf834ec9cba
Source RPM  : libpcap-1.7.4-1.fc23.src.rpm
Build Date  : Tue 30 Jun 2015 03:01:26 AM AEST
Build Host  : buildvm-16.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.tcpdump.org
Summary     : A system-independent interface for user-level packet capture
Description :
Libpcap provides a portable framework for low-level network...
```

Glad to provide more details.

Thanks

**Comment by guyharris** [comment] 2016-07-16 20:52
Ignore those test failures.

Those are really *libpcap* tests, not *tcpdump* tests, and the file version tests in question were added after libpcap 1.7.4 was released, so if you're building your version of tcpdump with the system libpcap, those tests will fail.  The failure has nothing to do with a problem with tcpdump; it has to do with older versions of libpcap not doing strict enough "is this a file version that I understand" test?

@fxlb Should we have a separate set of *libpcap* tests, and move those tests to a libpcap tests directory?

**Comment by bijalthanawala** [comment] 2016-07-17 00:03
Thanks @guyharris

**Comment by fxlb** [comment] 2016-07-17 11:15
@guyharris I will look at this issue.

**Comment by infrastation** [comment] 2017-02-07 12:50
I would just close this and accept the existence of the side effects caused by older libpcap versions.

**Comment by fxlb** [comment] 2017-02-07 14:11
Yes, no time for a better way now.

**Closed** 2017-02-07 14:13 UTC
